apiVersion: test/v1
kind: Config
metadata:
  name: get-patch-update-test
spec:
  namespace:
    number: 1
    prefix: test
  tuningSets:
  - name: UniformQPS
    qpsLoad:
      qps: 5
  steps:
  - name: Create 10 pods
    phases:
    - replicasPerNamespace: 10
      tuningSet: UniformQPS
      objectBundle:
      - basename: test-pod
        objectTemplatePath: pod.yaml

  - name: GET pods via APIResponsiveness
    measurements:
      - Identifier: "get-pods"
        Method: "APIResponsiveness"
        Params:
          action: get
          resource: pods

  - name: PATCH/UPDATE pod labels
    phases:
    - replicasPerNamespace: 10
      tuningSet: UniformQPS
      updateObject:
        objectTemplatePath: patch-pod.yaml
        fieldPath: "metadata.labels"