name: Auto Merge PR
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check for approval
        id: check_approval
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          APPROVALS=$(gh pr view $PR_NUMBER --repo $REPO --json reviews --jq '.reviews | map(select(.state == "APPROVED")) | length')
          echo "Found $APPROVALS approval(s)."
          if [[ $APPROVALS -gt 0 ]]; then
            echo "approved=true" >> $GITHUB_OUTPUT
          else
            echo "approved=false" >> $GITHUB_OUTPUT
          fi
      - name: automerge if approved
        if: steps.check_approval.outputs.approved == 'true'
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "lgtm"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "50"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          UPDATE_METHOD: "rebase"